# PSE:SM Candlestick Chart

Dataset: [PSE Dataset](https://www.kaggle.com/datasets/shanemaglangit/philippines-stock-exchange-dataset)

In [ ]:
import plotly.graph_objects as go
import pandas as pd

In [ ]:
df = pd.read_csv('stocks.csv')
df.head()

/tmp/ipykernel_1443/4023783116.py:1: DtypeWarning:

Columns (3,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.

,Stock Name,Code,Date,Price,Open,High,Low,Volume,Change%
0,Abra Mining and Industrial Corp,AR,"Mar 03, 2021",0.0046,0.0057,0.0071,0.0043,215.45B,-14.81%
1,Abra Mining and Industrial Corp,AR,"Mar 02, 2021",0.0054,0.0036,0.0054,0.0036,122.74B,50.00%
2,Abra Mining and Industrial Corp,AR,"Mar 01, 2021",0.0036,0.0035,0.0036,0.0033,5.89B,5.88%
3,Abra Mining and Industrial Corp,AR,"Feb 26, 2021",0.0034,0.0033,0.0036,0.0032,9.59B,0.00%
4,Abra Mining and Industrial Corp,AR,"Feb 24, 2021",0.0034,0.0038,0.0038,0.0032,29.68B,-12.82%

In [ ]:
df.drop(df[df['Code'] != 'SM'].index, inplace=True)
df.head()

,Stock Name,Code,Date,Price,Open,High,Low,Volume,Change%
254311,SM Investments Corp,SM,"Mar 24, 2021",970.00,951.50,970.00,950.00,168.43K,0.73%
254312,SM Investments Corp,SM,"Mar 23, 2021",963.00,952.00,967.50,952.00,298.06K,0.21%
254313,SM Investments Corp,SM,"Mar 22, 2021",961.00,950.00,968.00,940.00,327.88K,0.26%
254314,SM Investments Corp,SM,"Mar 19, 2021",958.50,990.00,"1,002.00",958.50,1.25M,-2.89%
254315,SM Investments Corp,SM,"Mar 18, 2021",987.00,"1,006.00","1,017.00",987.00,269.00K,-1.79%

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2155 entries, 254311 to 256465
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Stock Name  2155 non-null   object
 1   Code        2155 non-null   object
 2   Date        2155 non-null   object
 3   Price       2155 non-null   object
 4   Open        2155 non-null   object
 5   High        2155 non-null   object
 6   Low         2155 non-null   object
 7   Volume      2155 non-null   object
 8   Change%     2155 non-null   object
dtypes: object(9)
memory usage: 232.9+ KB

In [ ]:
def price_to_float(string):
  string = string.replace(',', '')
  return float(string)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.drop(columns=['Volume', 'Change%'])
for col in ['Price', 'Open', 'High', 'Low']:
  df[col] = df[col].apply(price_to_float)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2155 entries, 254311 to 256465
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Stock Name  2155 non-null   object
 1   Code        2155 non-null   object
 2   Date        2155 non-null   datetime64[ns]
 3   Price       2155 non-null   float64
 4   Open        2155 non-null   float64
 5   High        2155 non-null   float64
 6   Low         2155 non-null   float64
dtypes: datetime64[ns](1), float64(4), object(2)
memory usage: 199.2+ KB

In [ ]:
df.sort_values(by='Date', inplace=True)
df.head()

                 Stock Name Code       Date  Price   Open   High    Low
256465  SM Investments Corp   SM 2012-05-09  560.0  560.0  564.0  554.4
256464  SM Investments Corp   SM 2012-05-10  560.0  560.0  560.8  558.4
256463  SM Investments Corp   SM 2012-05-11  566.4  561.6  568.8  561.6
256462  SM Investments Corp   SM 2012-05-14  544.0  564.0  565.6  544.0
256461  SM Investments Corp   SM 2012-05-15  532.8  524.0  537.6  524.0

In [ ]:
df['Close'] = df['Open'].shift(-1)
df['Close'].iloc[-1] = df['Open'].iloc[-1]
df.head()

/tmp/ipykernel_1443/3504646472.py:2: FutureWarning:

ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


/tmp/ipykernel_1443/3504646472.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                 Stock Name Code       Date  Price   Open   High    Low  Close
256465  SM Investments Corp   SM 2012-05-09  560.0  560.0  564.0  554.4  560.0
256464  SM Investments Corp   SM 2012-05-10  560.0  560.0  560.8  558.4  561.6
256463  SM Investments Corp   SM 2012-05-11  566.4  561.6  568.8  561.6  564.0
256462  SM Investments Corp   SM 2012-05-14  544.0  564.0  565.6  544.0  524.0
256461  SM Investments Corp   SM 2012-05-15  532.8  524.0  537.6  524.0  536.0

In [ ]:
df.tail()

,Stock Name,Code,Date,Price,Open,High,Low,Close
254315,SM Investments Corp,SM,2021-03-18,987.0,1006.0,1017.0,987.0,990.0
254314,SM Investments Corp,SM,2021-03-19,958.5,990.0,1002.0,958.5,950.0
254313,SM Investments Corp,SM,2021-03-22,961.0,950.0,968.0,940.0,952.0
254312,SM Investments Corp,SM,2021-03-23,963.0,952.0,967.5,952.0,951.5
254311,SM Investments Corp,SM,2021-03-24,970.0,951.5,970.0,950.0,951.5

In [ ]:
fig = go.Figure(data=[go.Candlestick(x=df['Date'],
                open=df['Open'],
                high=df['High'],
                low=df['Low'],
                close=df['Close'])])
fig.show()

In [ ]:
fig.write_html("sm-2011-2021-candlestick.html")

# WHR Choropleth Map

Data Source: <a href="https://www.kaggle.com/datasets/unsdsn/world-happiness?select=2019.csv">           Kaggle</a>

In [57]:
!pip install pycountry

Collecting pycountry
  Downloading pycountry-26.2.16-py3-none-any.whl.metadata (12 kB)
Downloading pycountry-26.2.16-py3-none-any.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 56.6 MB/s eta 0:00:00
Installing collected packages: pycountry
Successfully installed pycountry-26.2.16

In [58]:
import pandas as pd
import pycountry
import plotly.graph_objects as go

In [ ]:
df = pd.read_csv('2019whr.csv')
df.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

In [ ]:
df = df.drop(columns=df.columns[3:9])
df = df.rename(columns={'Country or region': 'Country'})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Overall rank  156 non-null    int64
 1   Country       156 non-null    object
 2   Score         156 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 3.8+ KB

In [ ]:
def get_iso3(country_name):
  try:
    return pycountry.countries.lookup(country_name).alpha_3
  except LookupError:
    return None

df['Code'] = df['Country'].apply(get_iso3)
df.head()

   Overall rank      Country  Score Code
0             1      Finland  7.769  FIN
1             2      Denmark  7.600  DNK
2             3       Norway  7.554  NOR
3             4      Iceland  7.494  ISL
4             5  Netherlands  7.488  NLD

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Overall rank  156 non-null    int64
 1   Country       156 non-null    object
 2   Score         156 non-null    float64
 3   Code          146 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 5.0+ KB

In [ ]:
df.loc[df['Code'].isna() == True]

     Overall rank                  Country  Score  Code
38             39        Trinidad & Tobago  6.192  None
45             46                   Kosovo  6.100  None
63             64          Northern Cyprus  5.718  None
67             68                   Russia  5.648  None
78             79                   Turkey  5.373  None
98             99              Ivory Coast  4.944  None
102           103      Congo (Brazzaville)  4.812  None
109           110  Palestinian Territories  4.696  None
126           127         Congo (Kinshasa)  4.418  None
134           135                Swaziland  4.212  None

In order: TTO, XKX, None, RUS, TUR, CIV, COG, PSE, COD, SWZ

In [ ]:
codes_to_fill = ['TTO', 'XKX', None, 'RUS', 'TUR', 'CIV', 'COG', 'PSE', 'COD', 'SWZ']
na_indices = df.index[df['Code'].isna()]
for idx, code in zip(na_indices, codes_to_fill):
  df.at[idx, 'Code'] = code
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Overall rank  156 non-null    int64
 1   Country       156 non-null    object
 2   Score         156 non-null    float64
 3   Code          155 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 5.0+ KB

In [ ]:
fig = go.Figure(data=go.Choropleth(
    locations = df['Code'],
    z = df['Score'],
    text = df['Country'],
    colorscale = 'YlOrRd',
    autocolorscale=False,
    reversescale=True,
    marker_line_color='darkgray',
    marker_line_width=0.5,
    colorbar_title = 'Happiness Score',
))

fig.update_layout(
    title_text='2019 World Happiness Report',
    geo=dict(
        showframe=False,
        showcoastlines=False,
        projection_type='equirectangular'
    ),
    annotations = [dict(
        x=0.55,
        y=0.1,
        xref='paper',
        yref='paper',
        text='Data Source: <a href="https://www.kaggle.com/datasets/unsdsn/world-happiness?select=2019.csv">\
            Kaggle</a>',
        showarrow = False
    )]
)

fig.show()

In [ ]:
fig.write_html("2019whr.html")

# SEA World Bank Data GDP Per Capita Bar Race Animation

Datasource: [World Bank](https://data.worldbank.org/indicator/NY.GDP.PCAP.CD)

In [59]:
import pandas as pd
import plotly.express as px

In [44]:
df = pd.read_csv('gdp.pcap.csv')
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27441.550214,28440.041688,30082.158423,30645.890602,22759.807175,26749.329609,30975.998912,35718.753119,39498.594129,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,...,1334.470500,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,...,1630.039439,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2051.814621,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448,NaN

In [45]:
sea_countries = ["BRN", "KHM", "IDN", "LAO", "MYS", "MMR", "PHL", "SGP", "THA", "TLS", "VNM"]
df = df.loc[df['Country Code'].isin(sea_countries)]
df.drop(columns=['Indicator Code', '2025'], inplace=True)
df.rename(columns={'Country Name': 'Country', 'Country Code': 'Code', 'Indicator Name': 'Text'}, inplace=True)
df.head()

,Country,Code,Text,1960,1961,1962,1963,1964,1965,1966,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
31,Brunei Darussalam,BRN,GDP per capita (current US$),NaN,NaN,NaN,NaN,NaN,1028.884503,1145.705922,...,30625.128774,26663.297295,28024.382458,30988.119027,30426.573066,26834.359223,31006.963629,36632.928095,32890.549181,33153.473891
106,Indonesia,IDN,GDP per capita (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3288.222697,3521.469435,3798.883262,3860.953531,4106.948562,3853.702888,4287.173140,4730.834848,4876.307745,4925.430488
123,Cambodia,KHM,GDP per capita (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1547.320104,1675.195557,1826.353917,2036.673776,2225.877055,2081.739142,2167.403242,2325.030500,2429.748535,2627.879698
129,Lao PDR,LAO,GDP per capita (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2121.013391,2303.221560,2432.430595,2545.107542,2589.320810,2583.777307,2526.051050,2046.404403,2066.949798,2123.979094
160,Myanmar,MMR,GDP per capita (current US$),25.084776,27.265454,27.947004,25.803984,17.332201,15.117863,11.801322,...,1166.733055,1229.197135,1272.822418,1298.213103,1425.989542,1490.216836,1242.721344,1158.050051,1233.196662,1359.050016

In [46]:
df = df.melt(
    id_vars=["Country", "Code", "Text"],
    var_name="Year",
    value_name="GDP.PCAP"
)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 715 entries, 0 to 714
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Country   715 non-null    object
 1   Code      715 non-null    object
 2   Text      715 non-null    object
 3   Year      715 non-null    object
 4   GDP.PCAP  609 non-null    float64
dtypes: float64(1), object(4)
memory usage: 28.1+ KB

In [47]:
df.head()

             Country Code                          Text  Year   GDP.PCAP
0  Brunei Darussalam  BRN  GDP per capita (current US$)  1960        NaN
1          Indonesia  IDN  GDP per capita (current US$)  1960        NaN
2           Cambodia  KHM  GDP per capita (current US$)  1960        NaN
3            Lao PDR  LAO  GDP per capita (current US$)  1960        NaN
4            Myanmar  MMR  GDP per capita (current US$)  1960  25.084776

In [48]:
df.describe()

           GDP.PCAP
count    609.000000
mean    6405.721905
std    13411.544059
min       11.801322
25%      343.485225
50%     1164.200962
75%     3860.953531
max    90674.066633

Bar Race Animation wherein there is a set range

In [52]:
fig = px.bar(
    df,
    x='GDP.PCAP',
    y='Country',
    color='Country',
    orientation='h',
    animation_frame='Year',
    animation_group='Country',
    range_x=[0, 100000]
)

fig.show()

In [53]:
fig.write_html("wb_gdppcap.html")

Bar Race Animation autorange

In [54]:
fig = px.bar(
    df,
    x='GDP.PCAP',
    y='Country',
    color='Country',
    orientation='h',
    animation_frame='Year',
    animation_group='Country'
)

fig.update_layout(xaxis_autorange=True)

fig.show()

In [55]:
fig.write_html("wb_gdppcap-autorange.html")